language: node_js
node_js:
- 0.1
branches:
  only:
  - master
before_install:
- npm install -g "git+https://github.com/chenzaichun/hexo.git#2.8.3"
install:
- npm install
before_script:
- git config --global user.name 'Chen, Zai-Chun'
- git config --global user.email 'chenzaichun@gmail.com'
- git clone https://github.com/chenzaichun/hexo-theme-freemind.git themes/freemind
script:
- hexo generate
after_success:
# - mkdir .deploy
# - cd .deploy
# - git clone --depth 1 --branch master --single-branch $DEPLOY_REPO . || (git init
#   && git remote add -t master origin $DEPLOY_REPO)
# - rm -rf ./*
# - cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
# - git branch -m master
# - git push -q -u origin master
deploy:
  provider: heroku
  api_key:
    secure: DhXLOOeeIIIS+lw/WZrDmGViIDHCK66WRcWLlkGSpP+JCTxbZEQwO5Zibtxw/YAR8VQ3f5NY0hhGR8VaAmPmufJKbOU7+CD1owDx1BsfZ/x4N5jUWvdslskb27ulo7u5at82khrnK+gHASPUfBJiG8RsuqjXtO+E3sPWKtPKrdM=
  app: yesokay
  strategy: git
